apiVersion: v1
kind: ConfigMap

metadata:
  name: node-configmap
  namespace: devops-demo

data:
  PORT: "3001"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "devdb"
  LOG_LEVEL: "info"
  NODE_ENV: "development"
